trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'deepaannjohn/pipelines-javascript-docker'
  containerRegistryServiceConnection: 'DockerHub'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2